### ISSUE TITLE
Error while calling MQTT plugin

### ISSUE THREAD

**Issue by BozoLord** [OctoPrint/OctoPrint-MQTT#133]
Hi

I'm running Octoprint on a pi4 (Version 1.8.7) Version 1.0.0, running on Raspberry Pi 4 Model B Rev 1.4

my broker is mosquitto on my home assistant

I've installed mqtt plugin but it's not launching

Here's the logs:

2023-03-06 09:11:59,607 - octoprint.plugin - ERROR - Error while calling plugin mqtt
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/plugin/__init__.py", line 273, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint/util/__init__.py", line 1688, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_mqtt/__init__.py", line 185, in on_event
    self.mqtt_publish_with_timestamp(topic.format(event=event), data)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_mqtt/__init__.py", line 357, in mqtt_publish_with_timestamp
    return self.mqtt_publish(topic, payload, retained=retained, qos=qos, allow_queueing=allow_queueing)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_mqtt/__init__.py", line 360, in mqtt_publish
    if not (isinstance(payload, six.string_types) or raw_data):
AttributeError: module 'six' has no attribute 'string_types'

i've tried installing trhough ssh but it doesn't work either

how could I fix it ?
[octoprint (1).log](https://github.com/OctoPrint/OctoPrint-MQTT/files/10908975/octoprint.1.log)

**Comment by jneilliii** [comment]
This truly is a strange error. What it is complaining about is definitely in the docs for the six module. 

https://six.readthedocs.io/#six.string_types
