### ISSUE TITLE
Progress not reported correctly in the MQTT message

### ISSUE THREAD

**Issue by vlesquin** [OctoPrint/OctoPrint-MQTT#150]
Progress is reported as 0 in the MQTT message.

#### Version of OctoPrint
1.10.2

#### Version of the MQTT plugin
0.8.16

#### Used MQTT broker and its version
Mosquito 6.4.1
 
#### Related content in octoprint.log

2024-08-31 16:57:52,328 - octoprint.plugin - ERROR - Error while calling plugin mqtt
Traceback (most recent call last):
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint/plugin/__init__.py", line 275, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint/util/__init__.py", line 1686, in wrapper
    return f(*args, **kwargs)
  File "/octoprint/plugins/lib/python3.10/site-packages/octoprint_mqtt/__init__.py", line 178, in on_event
    self.progress_timer = RepeatedTimer(5, self._update_progress, [payload["origin"], payload["path"]])
TypeError: 'NoneType' object is not subscriptable

Thanks for the support !

**Comment by viktak** [comment]
Works fine for me @ OctoPrint 1.11.3 Python 3.10.15
