### ISSUE TITLE
Expection in plugin when adding temprature point

### ISSUE THREAD

**Issue by SoundGuy** [OctoPrint/OctoPrint-MQTT#42]
#### What were you doing?
I updated octoprint to the latest version. 
I have both MQTT and IFTT plugins installed 
IFTT started spamming ClientOpened messages every few seconds = disabling MQTT plugin made it stop 
i saw errors in the log

#### What did you expect to happen?

no errors.  and no ClientOpen messages every few seconds

#### What happened instead?
errors:

the client causes something to crash with other plugins (IFTTT plugin keeps sending the OpenClient message ) and I see these errors in the log 

#### Version of OctoPrint
OctoPrint 1.3.8 running on OctoPi 0.14.0

#### Version of the MQTT plugin
MQTT (0.7.1)

#### Link to octoprint.log

Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 145, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature
    or abs(value["actual"] - self.lastTemp[key]["actual"]) >= threshold \
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2018-05-13 15:30:53,387 - octoprint.printer.standard - ERROR - Exception while adding temperature data point to callback <mqtt.MqttPlugin object at 0xb4
03b090>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 145, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature
    or abs(value["actual"] - self.lastTemp[key]["actual"]) >= threshold \
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2018-05-13 15:30:55,370 - octoprint.printer.standard - ERROR - Exception while adding temperature data point to callback <mqtt.MqttPlugin object at 0xb4
03b090>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 145, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature
    or abs(value["actual"] - self.lastTemp[key]["actual"]) >= threshold \
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
2018-05-13 15:30:56,298 - octoprint.plugins.IFTTTmaker - INFO - URL: https://maker.ifttt.com/trigger/op-ClientOpened/with/key/dUWVcmGy4B_FUwT8D0Zgit
2018-05-13 15:30:56,331 - octoprint.plugins.IFTTTmaker - INFO - Trigger: op-ClientOpened Response: Congratulations! You've fired the op-ClientOpened event Payload: {'value3': '192.168.1.108', 'value2': '', 'value1': ''}
2018-05-13 15:30:56,443 - octoprint.server.util.sockjs - INFO - New connection from client: 192.168.1.108
2018-05-13 15:30:56,521 - octoprint.plugins.IFTTTmaker - INFO - Event skipped: ClientClosed
2018-05-13 15:30:57,404 - octoprint.printer.standard - ERROR - Exception while adding temperature data point to callback <mqtt.MqttPlugin object at 0xb403b090>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 145, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature

Do you need the full log or is this engouh?

**Comment by foosel** [comment]
I have my hands full with core OctoPrint development and haven't had a chance to look into this yet.

**Comment by SoundGuy** [comment]
i'm still getting this error flooding my log. 

2018-10-11 17:42:22,490 - octoprint.printer.standard - ERROR - Exception while adding temperature data point to callback <mqtt.MqttPlugin object at 0xb307b030>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 167, in _sendAddTemperatureCallbacks
    callback.on_printer_add_temperature(data)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 204, in on_printer_add_temperature
    or abs(value["actual"] - self.lastTemp[key]["actual"]) >= threshold \
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'

just curious if this is serious or not. my octoprint crashes every once in a while (week-two) and it did once in mid print and this flood of errors is making it hard to find anything else

**Comment by jneilliii** [comment]
@SoundGuy, I just checked this on my OctoPrint 1.3.9 running on OctoPi 0.14.0 and am not getting this temperature error.  Not sure if this is a conflict with IFTT or maybe something was fixed between version 1.3.8 and 1.3.9 of OctoPrint that resolves this issue.

**Comment by SoundGuy** [comment]
I’m on the same config. 1.3.9 with 0.14 

Oded Sharon

Email:  iPhone@odedsharon.com
Skype: soundguy27 | Twitter: @SoundGuy | Facebook:oded.sharon  | LinkedIn: SoundGuy  | Blog: http://odedsharon.com


(sent from my iPhone so probably there are some typos)

**Comment by jneilliii** [comment]
Do you get the same noise in your log with the ifttt plugin disabled?

**Comment by sidddy** [comment]
@jneilliii : The temperature graph handles it properly: After "host-only" startup the graph shows only the tool temperature (off). Once the MCU goes online, the bed temperature line appears.

![image](https://user-images.githubusercontent.com/13465394/47970104-389cc000-e081-11e8-8b64-f4e32ca8bc58.png)

**Comment by tedder** [comment]
On it. Aside from this error, there's a really subtle error that I didn't see at first:
```
        if key not in self.lastTemp or \
            or abs(value["actual"] - self.lastTemp[key]["actual"]) >= threshold \
            or value["target"] != self.lastTemp[key]["target"]:
```

4 internet points to whoever spots it :)

**Comment by tedder** [comment]
doh- actually I did that when I was doing some debugging, that's not the committed version.

**Comment by jneilliii** [comment]
Double or?

**Comment by tedder** [comment]
Yeah, fun times eh?

I have the fix committed, I'll make a PR after 0.8 ships.

**Comment by tedder** [comment]
I'd rather roll this into 0.8.1 with other minor fixes. That way we can get the other stuff out the door first.

(can you tell I do devops/release management for a career?)

**Comment by jneilliii** [comment]
No problem.  I barely understand git and have never worked with other programmers on a team, so if you see me doing something wrong on this project, or you guys want to manage it differently I'm all ears.  This one is a little different because it was left over from before, I just made minor tweaks directly to devel branch.  Moving forward I guess we should come up with a development workflow, let me know your thoughts.

**Comment by sidddy** [comment]
@tedder: as far as I can see, there's a little copy-paste-error in your commit, see https://github.com/OctoPrint/OctoPrint-MQTT/commit/9fc3e60e4198f47e33038f40c4092b7b0a4fcec9#r31176383

With that propsed change, your coding is working fine for me, the exception is gone and temperatures are properly reported via mqtt.
