### ISSUE TITLE
The MQTT plugin suddenly stopped publishing information.

### ISSUE THREAD

**Issue by TheLion** [OctoPrint/OctoPrint-MQTT#51]
#### What were you doing?

The MQTT plugin suddenly stopped publishing information.

#### Version of OctoPrint

v1.3.9

#### Version of the MQTT plugin
v0.7.1

Using Mosquitto on a remote Raspberry Pi.

Áll was working fine, until october 18th. Since that time, the debug of the MQTT plugin displays some errors and isn't connecting to the MQTT broker.

```
2018-11-02 18:25:42,707 - octoprint.plugins.mqtt - INFO - Settings changed (broker_diff={}, lw_diff={'lw_active': False, 'lw_topic': None}), reconnecting to broker
2018-11-02 18:25:43,721 - octoprint.server.api.settings - ERROR - Could not save settings for plugin MQTT (0.7.1)
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/settings.py", line 535, in _saveSettings
    plugin.on_settings_save(data["plugins"][plugin_id])
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 148, in on_settings_save
    self.mqtt_connect()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 273, in mqtt_connect
    self._mqtt.tls_set(ca_certs, **tls_args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 764, in tls_set
    context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory
2018-11-02 18:25:45,087 - octoprint.plugins.mqtt - DEBUG - Not connected, enqueuing message: octoprint/temperature/tool0 - {"_timestamp": 1541179545, "actual": 19.77, "target": 0.0}
2018-11-02 18:25:48,895 - octoprint.plugins.mqtt - DEBUG - Not connected, enqueuing message: octoprint/temperature/bed - {"_timestamp": 1541179548, "actual": 23.06, "target": 0.0}
2018-11-02 18:25:50,909 - octoprint.plugins.mqtt - DEBUG - Not connected, enqueuing message: octoprint/temperature/bed - {"_timestamp": 1541179550, "actual": 23.16, "target": 0.0}
2018-11-02 18:25:52,905 - octoprint.plugins.mqtt - DEBUG - Not connected, enqueuing message: octoprint/temperature/tool0 - {"_timestamp": 1541179552, "actual": 19.88, "target": 0.0}
2018-11-02 18:25:52,917 - octoprint.plugins.mqtt - DEBUG - Not connected, enqueuing message: octoprint/temperature/bed - {"_timestamp": 1541179552, "actual": 23.06, "target": 0.0}
```
Also when trying to connect it to a temporary locally installed MQTT broker, the same error is displayed.

```
2018-11-02 18:33:38,978 - octoprint.plugins.mqtt - DEBUG - Not connected, enqueuing message: octoprint/temperature/bed - {"_timestamp": 1541180018, "actual": 22.06, "target": 0.0}
2018-11-02 18:33:40,503 - octoprint.plugins.mqtt - INFO - Settings changed (broker_diff={'url': u'127.0.0.1'}, lw_diff={}), reconnecting to broker
2018-11-02 18:33:41,518 - octoprint.server.api.settings - ERROR - Could not save settings for plugin MQTT (0.7.1)
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/api/settings.py", line 535, in _saveSettings
    plugin.on_settings_save(data["plugins"][plugin_id])
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 148, in on_settings_save
    self.mqtt_connect()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_mqtt/__init__.py", line 273, in mqtt_connect
    self._mqtt.tls_set(ca_certs, **tls_args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 764, in tls_set
    context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory
2018-11-02 18:33:43,172 - octoprint.plugins.mqtt - DEBUG - Not connected, enqueuing message: octoprint/temperature/tool0 - {"_timestamp": 1541180023, "actual": 19.53, "target": 0.0}
2018-11-02 18:33:44,972 - octoprint.plugins.mqtt - DEBUG - Not connected, enqueuing message: octoprint/temperature/tool0 - {"_timestamp": 1541180024, "actual": 19.73, "target": 0.0}
```

Already tried removing the plugin and re-installing it, but that didn't change anything. Rebooted Octoprint RPi completely, no change.

What can this be?

Regards,

Martijn

**Comment by TheLion** [comment]
Never mind. Solved it by uninstalling the plugin and removing all configuration from config.yaml.
